title: Team MCPA
description: Software for <strike>multichannel</strike> multivariate pattern analysis of fNIRS data
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
