title: TeamMCPA
description: Software for <strike>multichannel</strike> multivariate pattern analysis of functional near-infrared spectroscopy (fNIRS) data
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
